## levantamiento de base de datos en contenedor para desarrollo

version: '3.8'

services:
  bank-db:
    container_name: bank_digital_db
    image: postgres:15.3
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data   # mantener la data
    ports:
      - 5433:5432                         # local/contenedor
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=bank_db